### PR TITLE
Adopt addon under new ownership

### PR DESCRIPTION
**Pull request by Alonski**
This mainly fixed and allowed deploying of the addon docs.
Making a few updates/fixes:

- Replaced all instances of `tim-evans` with `adopted-ember-addons`
- Replaced package-lock with yarnlock
- Removed bowerrc

### CODE REVIEW

**Comment by tim-evans** [comment]
Does someone need npm credentials??

**Comment by tim-evans** [comment]
Ok! I'm trying to be careful with handoffs here, since there's some security ramifications. The [recent security](https://github.com/dominictarr/event-stream/issues/116) concerns with transferring rights are still on my mind.

In the spirit of keeping the transfer safe for all of the folks using `ember-file-upload`, could you have at least 2 other folks vouch for you (here is ok). In addition, please provide your npm username, so I can add you as soon as this process is over.

Thanks so much, and I hope you understand that the process I'm imposing here isn't diminishing your efforts and help ❤️

**Comment by Alonski** [comment]
@knownasilya @MelSumner @locks @jessica-jordan 
Can you vouch for me please 😄 
@tim-evans I completely understand your concern. I am actually working on something for that exact issue that is still in the secret alpha phase 😅 
I am on the Ember Times team and. I think, that I am a bit known in the community.
Here is my NPM User:
https://www.npmjs.com/~alonbukai

Thanks a lot! I am available to chat on Discord as well `@alon`

**Comment by knownasilya** [comment]
Vouching for @Alonski

**Comment by tim-evans** [comment]
@Alonski I've added you as an npm admin :)

**Pull request merged**
