### PR TITLE
Fixes #174 - Enable dropdown without upload

### LINKED ISSUE #174: Enable support for file-dropzone without file-upload
I have raised a [full issue](https://github.com/kaliber5/ember-bootstrap/issues/672) in the EmberBootstrap repository as I'm pretty sure that is the root cause of the issue, however I thought I would raise it for anyone else who uses both addons and incase you guys can shed some light on how the dropzone and file upload components work that could help me resolve the issue.

### PR DESCRIPTION
**Pull request by fran-worley**
Fixes #174 

@tim-evans I've tested this locally and it works, I'm not sure how you want me to test this as there aren't any component tests.

### CODE REVIEW

**Comment by tim-evans** [comment]
Could you add some documentation along with this PR? If you're able to, I'd also appreciate if there's some guidance around what's accessibility best-practices for this (having a file-picker for a drop zone is _ideal_)

**Comment by fran-worley** [comment]
Docs yes, I’ll do that today.

For accessibility, the biggest issue seems to be that divs are not keyboard navigateable and without an input at all there is no way to interact with it without a mouse/ touchscreen.

There seems to be 2 approaches to fix this and I’d be interested to know your preference:

1. add tab index to the dropzone root element and add handling for keyboard events

2. In the dropzone element we add an input visible for the browser but not user (w0, h0 opacity0 etc). 
This option is my preference but can you see any issues with having a file-input for the dropzone component and another for the file-upload component.

There are also no aria-* attributes set on this like label or role etc which I think is also an issue for file-upload. If this is something we should address too I’d suggest a separate PR.

**Comment by tim-evans** [comment]
Thanks for the thorough comment!

I _think_ that it's currently ok with the implementation since the DOM elements being used are accessible, but definitely there's something to look at with dropzones. I imagine that using voice-over or some other assistive technologies would mean that dropzones aren't useful, but I've used it only sparingly, and not in a full app setup.

**Comment by fran-worley** [comment]
@tim-evans do you have any idea why the test-suite won't run? I can't get it running locally or in travis something to do with the doc generator...

**Comment by tim-evans** [comment]
Oh, hmm, I can take a look soon 😭

**Comment by tim-evans** [comment]
Oh gosh, sorry about not following up. I've been a bit distracted. I think the upgrade I did may help? :/

**Comment by fran-worley** [comment]
@tim-evans thanks for the upgrades, I'll rebase and see what's what :) Probably won't be till later this week but I'll see how I get on.

**Comment by tim-evans** [comment]
Thanks @fran-worley to fix this more long term, I'm trying to find a happy home for these addons

**Comment by Alonski** [comment]
Hey @fran-worley I have taken over maintaining this addon.
Do you feel as if this PR is ready to be merged?

**Comment by Alonski** [comment]
@fran-worley Would love to see this revisited. If not then this will be closed soon 🙂

**Comment by fran-worley** [comment]
@Alonski I'll try and take a look this week I think all it needs is a rebase...

**Comment by gilest** [comment]
@Alonski this can be closed now. Merged in #276

**Comment by Alonski** [comment]
Closed by #276

**Pull request closed without merging**
