### PR TITLE
automate releases

### PR DESCRIPTION
**Pull request by jelhan**
This setups `release-it` and `lerna-changelog` to automate the release process. It also documents the required process in `RELEASE.md`.

Before doing the release the pull requests must be labeled correctly to be picked up by lerna-changelog.

This is based on [`rwjblue/create-rwjblue-release-it-setup`](https://github.com/rwjblue/create-rwjblue-release-it-setup). The first commit uses the current defaults. Second commits applies the changes proposed in https://github.com/rwjblue/create-rwjblue-release-it-setup/pull/15.

It's splitted in two commits to ease review. Please squash on merging.

### CODE REVIEW

**Comment by jelhan** [comment]
> error semver@7.1.3: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"

Seems like a dependency dropped node 8 support without doing a major release. :disappointed:

**Comment by gilest** [comment]
Cool tooling. Looks good to me 👀

**Comment by jelhan** [comment]
Rebased after #308 has been merged. Tests should pass now.

**Comment by jelhan** [comment]
> I have gone through the PRs since the last version and tried to label them. Probably worth double-checking the labels I have used are correct.

You motivated me to do the same for the other PRs and update the changelog which was very outdated. This also includes a nice example of how the generated changelog looks like into this pull request.

**Comment by gilest** [comment]
I think this branch needs a rebase.

Love the new changelog <3

**Comment by jelhan** [comment]
Rebased.

**Comment by Alonski** [comment]
Sorry for not reviewing but it seems that you both are doing an amazing job! @jelhan and @gilest 
Awesome work!

**Pull request merged**
