### PR TITLE
enable dropping directories

### PR DESCRIPTION
**Pull request by bekzod**
chrome and some other browsers support [webkitGetAsEntry](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry) which enables dropping directories to dropzone

### CODE REVIEW

**Comment by tim-evans** [comment]
I'm interested in this, but am worried about having this feature in that may get dropped at any time by browser vendors (since it's non-standard)

**Comment by Alonski** [comment]
@bekzod Would love to see this revisited. If not then this will be closed soon 🙂

**Comment by jelhan** [comment]
I don't think the `webkitGetAsEntry` API is a safe bet for the future. No vendor seems to support it. Google Chrome team pushes [Native File System API](https://wicg.github.io/native-file-system/).

**Comment by jelhan** [comment]
Closing as this seems to be stale. Feel free to repoen or open another pull request based on this one.

**Pull request closed without merging**
