### PR TITLE
Fix this-property-fallback deprecation

### PR DESCRIPTION
**Pull request by aoumiri**
This PR solves #449

### CODE REVIEW

**Review by jelhan — APPROVED** [review]
Thanks a lot for picking this one up.

In many cases `{{this.foo}}` is the same as `{{@foo}}`. But as the arguments are defined as properties on the component class I agree that we should reference it in the template. Everything else would be consuming. We should refactor to `{{@foo}}` when migrating to `@glimmer/component`.

**Comment by jelhan** [comment]
> > In many cases `{{this.foo}}` is the same as `{{@foo}}`. But as the arguments are defined as properties on the component class I agree that we should reference it in the template. Everything else would be consuming. We should refactor to `{{@foo}}` when migrating to `@glimmer/component`.
> 
> I was wondering if I should change that too, but I figured it would be a bit more adventurous refactoring. I would be happy to do it in another PR though smile

A pull request to refactor the components to `@glimmer/component` is very welcome.

**Comment by jelhan** [comment]
@gilest This change seems safe to me. Is it okay for you to merge even though CI is failing current and release as the last version of v3?

**Comment by gilest** [comment]
@jelhan yes seems fine to me too. Go ahead and merge

**Review by gilest — APPROVED** [review]

**Comment by aoumiri** [comment]
Thanks everyone for your help!

**Comment by gilest** [comment]
Thank you @aoumiri

**Comment by jelhan** [comment]
Published as [`v3.0.6`](https://github.com/adopted-ember-addons/ember-file-upload/releases/tag/v3.0.6).

**Pull request merged**
